name: 'Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:

  # Only checking latest Linux/UNIX on pulls to save execution times
  test-main-pulls:
    if: github.event_name == 'pull_request'
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'macos-latest'
          - 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1
      - name: 'Install Dependencies'
        run: './test/install_deps.sh'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'

      - uses: 'docker/setup-buildx-action@v3'
        if: contains(matrix.os, 'ubuntu')
        with:
          install: true
      - uses: 'docker/build-push-action@v5'
        if: contains(matrix.os, 'ubuntu')
        with:
          context: .
          load: true
          tags: "tofuenv-tofu:${{ github.sha }}"
      - name: 'Check Dockerfile'
        if: contains(matrix.os, 'ubuntu')
        run: |
          expect=1.6.0-rc1;
          got="$(docker run -e "TOFUENV_TOFU_VERSION=${expect}" "tofuenv-tofu:${{ github.sha }}" version)";
          echo "${got}" | tee /dev/stderr | grep -e 'OpenTofu v1.6.0-rc1'

  # When we push to main, test everything in order to guarantee releases
  test-main-pushes:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - 'macos-11'
          - 'macos-10.15'
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
          - 'windows-2019'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1
      - name: 'Install Dependencies'
        run: './test/install_deps.sh'
      - name: 'Run all tests'
        run: './test/run.sh'
        shell: 'bash'

      - uses: 'docker/setup-buildx-action@v3'
        if: contains(matrix.os, 'ubuntu')
        with:
          install: true
      - uses: 'docker/build-push-action@v5'
        if: contains(matrix.os, 'ubuntu')
        with:
          context: .
          load: true
          tags: 'tofuenv-tofu:latest'
      - name: 'Check Dockerfile'
        if: contains(matrix.os, 'ubuntu')
        run: |
          expect=1.6.0-rc1;
          got="$(docker run -e "TOFUENV_TOFU_VERSION=${expect}" tofuenv-tofu:latest version)";
          echo "${got}" | tee /dev/stderr | grep -e 'OpenTofu v1.6.0-rc1'
